### PR TITLE
Improve multi platform support

### PR DESCRIPTION
**Pull request by piste-jp**
This PR includes following changes. 

- Add a backend to check the I/F
- Enable to build on Linux

### CODE REVIEW

**Comment by piste-jp** [comment]
Hi @manu0401,

Could you check my change? I confirm my change can be built on Linux. But I didn't conform that my change doesn't break the NetBSD code.

Of cause, I can build NetBSD environment on my machine but I will make an auto confirmation framework that checks contributor to LTFS doesn't break this project because of unawareness backend I/F change. So it is very helpful if you can check my code and merge this to this project.

**Comment by manu0401** [comment]
On Mon, Feb 25, 2019 at 09:55:41PM -0800, Atsushi Abe wrote:
> Could you check my change? I confirm my change can be built on Linux. But I didn't conform that my change doesn't break the NetBSD code.

Um, I thought I have pushed the Linux and MacOS X stuff, but it
seems I did not. It contains most of your changes, plus the 
actuel code for Linux and MacOS X. Please let me send a pullup
request for it.

-- 
Emmanuel Dreyfus
manu@netbsd.org

**Comment by manu0401** [comment]
> Um, I thought I have pushed the Linux and MacOS X stuff, but it
> seems I did not. It contains most of your changes, plus the
> actuel code for Linux and MacOS X.

I pushed it to master (while I wanted to make a pull request, but
let us consider that as part of the initial import).

Could you please rebase?

-- 
Emmanuel Dreyfus
manu@netbsd.org

**Comment by piste-jp** [comment]
Sure. I created a new PR.

**Pull request closed without merging**
